### ISSUE TITLE
Error on PhantomJs

### ISSUE THREAD

**Issue by tgirardi** [derhuerst/is-roughly-equal#2]
Im running Jasmine BDD tests using phantomjs and no spec runs if I include this module on my code. The only error that gets printed is:

`No specs executed, is there a configuration error?`

If I remove the module import, my specs run correctly.

I'm using a polyfill for `Object.assign` (which is not supported on PhantomJs, I believe), but it doesn't solve the problem

**Comment by derhuerst** [comment]
Sounds like the behavior of PhantomJS that I also stumbled upon: phantom just stops executing if there's a syntax error. AFAIK, ES6 arrow functions are not supported in PhantomJS yet.

You have two choices
- rewrite `is-roughly-equal` in ES5 syntax
- use a transpiler like [Babel](http://babeljs.io/)

**Comment by tgirardi** [comment]
@derhuerst weird. I'm using a transpiler.

I didn't know about that behavior on syntax error. Now I know what I have to look for. I was thinking about running a small transpiled code that just imports is-roughly-equal and try to find a syntax error that is not being solved by transpilation. However, I have not much experience running code on phantomjs.

Rewriting in ES5 syntax is a good option if I give up after some attempts.

**Comment by derhuerst** [comment]
> I didn't know about that behavior on syntax error. Now I know what I have to look for. I was thinking about running a small transpiled code that just imports is-roughly-equal and try to find a syntax error that is not being solved by transpilation.

Hm, with transpilation I would expect it to work. Can you show me the code?

> However, I have not much experience running code on phantomjs.

Me neither, it was just an educated guess.

**Comment by tgirardi** [comment]
@derhuerst my mistake ... 😅

I checked the bundled file created by webpack and the code corresponding to is-roughly-equal was in fact not transpiled.

I was using the following exclude option in webpack.config.js, which is pretty common:

``` js
exclude: /node_modules/,
```

Adjusting the regexp to the following fixes the problem:

``` js
exclude: /node_modules\/(?!(is-roughly-equal)\/).*/,
```

I could just close this issue, however, I believe that most npm packages include some sort of way of ensuring that a transpiled version of the code is used when importing the module, and not the original source code (I'm don't know much about npm, but I suppose that during the final process of an `npm install` some sort of post-process script is run that "builds" the module)

Shouldn't this module also ensure the use of a transpiled version when importing the module?

**Comment by derhuerst** [comment]
See #3.
